services:
  - type: web
    name: ifta-tax-system
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Configuración de la base de datos PostgreSQL
      - key: DB_DIALECT
        value: postgres
      - key: DB_HOST
        value: dpg-d1qkcrq4d50c739cr9r0-a
      - key: DB_PORT
        value: '5432'
      - key: DB_NAME
        value: iftareports_postgres
      - key: DB_USER
        value: iftareports_postgres_user
      - key: DB_PASSWORD
        value: jeOwt4kTSO1HZQzAlp5sSfXTu9iSpzUk
      # Configuración de JWT
      - key: JWT_SECRET
        value: 83d5a72761848da1d21b94e47869b46971ae17c99117ecaa9fcbad61cdb3d454
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: JWT_COOKIE_EXPIRES_IN
        value: '90'

# Si necesitas una base de datos PostgreSQL
# databases:
#   - name: ifta_db
#     databaseName: ifta_db
#     user: ifta_user
#     plan: free
